### ISSUE TITLE
[BUG] config files are ignored

### ISSUE THREAD

**Issue by Sanduhr32** [hypherionmc/simple-rpc-public#10]
**Describe the bug**
Modify the simple-rpc-server.json for not pushing your servers ip to 100k+ via discord precense update events.

**To Reproduce**
1. Go to '$installLocation/config/simple-rpc-server.json'
2. Remove '%ip%' from the description.
3. Save the file
4. Start MC & join a server

**Expected behavior**
1. The config has been loaded & applied
2. Your servers ip isn't displayed in your discord rpc.

**Screenshots**
![image](https://lets-go-on-a.date/san-60a7fe91uOiSiJY12vwI.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 64-Bit (10.0.19042) / Debain 11 (kernel 5.10.0.6)
 - JAVA Version: 8 build 51 64bit, aka default java version mc 1.16.5 is shipped with 
 - Mod Version: 1.16.5-version
 - Discord Version: Canary 85578 (44da658), Host 1.0.32, Windows 10 64-Bit (10.0.19042)
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.16

**Additional context**
Privacy

**Comment by hypherionmc** [comment]
@Sanduhr32 Firstly, is the server side set to "enabled": true in the config file? 

Secondly, just remove (%ip%) from both the client side and server config file

**Comment by Sanduhr32** [comment]
I have to change a config of a client side mod on the server?

**Comment by hypherionmc** [comment]
If "enabled" is set to false in "simple-rpc-server.json", it reads the values of the config file on the client

**Comment by Sanduhr32** [comment]
well which? there is one nested in 'multi_player' and one in the first scope.

**Comment by hypherionmc** [comment]
For more clarity:

The "simple-rpc-server.json" file is ALWAYS ignored on your client, except when playing a lan game.

So if you have simple RPC installed on your server and your want to override values, you need to change "enabled": false to "enabled": true and it will push the values from your server to the client.

Otherwise, just make the changes to "simple-rpc.json"

**Comment by Sanduhr32** [comment]
I guess i should read the wiki before complaining.
Tho this is very unconvenient set up that it doesn't warn you about a server overriding the local config for a client side mod.

**Comment by hypherionmc** [comment]
It doesn't override unless the simple-rpc-server.json file has enabled set to true....

**Comment by Sanduhr32** [comment]
the modpack does exactly that. I wasn't aware that a server override was possible. I appreciate for your help and am sorry for being a prick.

**Comment by hypherionmc** [comment]
No worries, I'll make the docs a bit clearer next time and remove it being a default value in a brand new config file

**Comment by Sanduhr32** [comment]
I updated the issue with a TL;DR if anyone ever forgets to read. Btw the wiki of this repo should redirect to https://docs.hypherionmc.me/books/simple-rpc-user-manual/ instead or be sycnchronized with it.
