### ISSUE TITLE
Crash on Startup (New Instance)

### ISSUE THREAD

**Issue by TheComputerizer** [hypherionmc/simple-rpc-public#11]
**Describe the bug**
I added this to a small testing instance so I could generate a config file to edit and put in my pack without the 10+ min loading time, but it ended up crashing instead. These are all mods I have in my main instance anyways.

**To Reproduce**
1. Run with the same list of mods that I do (see the linked log file)

**Expected behavior**
To start up so I can generate a config

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10
 - JAVA Version: 1.8.0.291
 - Mod Version: 1.12.2-2.1.1-all
 - Discord Version: N/A in this case since its a startup crash
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2855

**Additional context**
As stated above, this is a fresh install before generating the config. In fact, the [log](https://pastebin.com/D3c4edMG) even seems to point to the config that tries to generate.

**Comment by TheComputerizer** [comment]
Not quite sure why, but it starts up just fine in my main instance. I assume whatever this crash is could be an issue though in certain cases though.

**Comment by hypherionmc** [comment]
Hi. Thanks for reporting. This is a known issue with the current release.

It's only an issue with new instances where there isn't already a config file present. If you restart the game after it crashed, it will load up successfully. This will be fixed in the next release

**Comment by hypherionmc** [comment]
Fixed in 2.2
