### ISSUE TITLE
[BUG] Game hangs on startup.

### ISSUE THREAD

**Issue by JoeJoeTV** [hypherionmc/simple-rpc-public#12]
**Describe the bug**
When I try to start the game with this mod installed(also tested with only this mod and fabric-api), the game hangs after "[Indigo] Registering Indigo renderer!"

**To Reproduce**
1. Install this mod, aswell as fabric-api
2. Try to start the game

**Expected behavior**
The game should start normally and nothang at startup

**Logs**
Here is the latest log: https://pastebin.com/0f7uGVh2

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Linux Mint Cinnamon 20.1 64bit
 - JAVA Version: AdoptOpenJDK 8/11/16 (Didn't work with any Java version)
 - Mod Version: 2.2.2-fabric
 - Discord Version: Stable 91104 (7111d55) / Host 0.0.15
 - Minecraft Version: 1.16.5
 - Fabric Loader Version: 0.11.6
 - Fabric API Version: 0.37.1

**Comment by hypherionmc** [comment]
Okay just did a quick test on windows, and the game loads up fine. I'll setup a linux VM later to test if this is another linux related issue or not

**Comment by JoeJoeTV** [comment]
Ok, now this is weird, I did some more testing and saw that Minecraft starts with Discord closed and I tried it again after starting it again and now it works just fine. I restarted again and it still worked, so I'm going to close this issue now, since it works now, but if it stops working again, I will add a comment here.

**Comment by hypherionmc** [comment]
Thanks for the feedback. I'll still investigate so make sure this isn't a mod issue
