### ISSUE TITLE
[BUG] RPC 1.18 version 2.4beta for fabric is not working with fabric api 0.43.1+1.18

### ISSUE THREAD

**Issue by OMASHE** [hypherionmc/simple-rpc-public#18]
**Describe the bug**
Minecraft 1.18 will not launch when simple discord rpc is used

**To Reproduce**
1. Use simple-rpc-1.18_experimental-snapshot-1-2.4-beta-fabric.jar on minecraft 1.18
2. Have an up to date fabric api
3. Launch game

**Expected behavior**
Game will crash on launch 

**Screenshots**
![image](https://user-images.githubusercontent.com/38072826/144538467-dc8139c9-0bca-40d8-994a-70b9bf5d5749.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11 Home
 - JAVA Version: java 17.0.1 2021-10-19 LTS
 - Mod Version: simple-rpc-1.18_experimental-snapshot-1-2.4-beta-fabric
 - Discord Version: Stable 106713 (4ac52ea)
 - Minecraft Version: 1.18
 - Fabric Version: 1.18 | Fabric Loader 0.12.8

**Additional context**

**Comment by hypherionmc** [comment]
Hi. Thanks for reporting. Okay looks like it wants the fabric api for the experimental builds. I'll do a fix for it, then if you don't mind you can test it for me and I'll push a fix

**Comment by hypherionmc** [comment]
You can test this one: https://ci.firstdarkdev.xyz/job/Simple%20RPC/job/Fabric/job/1.18%20(Fabric)/15/artifact/build/libs/simple-rpc-1.18-2.6-beta-dev-15-fabric.jar. If it works, I'll push a fix to Curseforge

**Comment by OMASHE** [comment]
That one is working for me I tested on fabric-api-0.43.1 and then also on 0.44.0, everything seems to be working for me. 
![image](https://user-images.githubusercontent.com/38072826/144634725-ff4aeefb-819c-4bed-b2ae-ee7241a932f5.png)

Thanks!
