### ISSUE TITLE
[BUG] RPC is not updated if I press esc on the server list

### ISSUE THREAD

**Issue by Oondanomala** [hypherionmc/simple-rpc-public#19]
**Describe the bug**
If I open the server list and close it pressing esc the text will not update

**To Reproduce**
1. Set something different for both main menu event and server list event
2. Open the server list and close it by pressing esc
3. The discord rpc hasn't been updated to show the main menu text

**Expected behavior**
The text changes back to whatever I have for the main menu

**Versions:**
 - OS: Windows 10
 - JAVA Version: 17.0.1 x64
 - Mod Version: 2.5.1 Beta
 - Discord Version: Stable 106905
 - Minecraft Version: 1.18
 - Fabric Version: 0.12.8

**Additional context**
The text updates if i click any button that sends me back to the main menu, not just the one in the server list

**Comment by hypherionmc** [comment]
Hmm odd. The RPC is supposed to update each time the screen is changed. I'll check it out
