### ISSUE TITLE
[BUG] Does not realize you are not in a server.

### ISSUE THREAD

**Issue by DaddySpin** [hypherionmc/simple-rpc-public#2]
**Describe the bug**
The mod does not realize you are not in a server when server list is disabled.

**To Reproduce**
1. go in config and disable server list
2. join a server and then exit
3. while on the server list menu it will still say you are in that server
4. and only when you enter the main menu again does it realize you are not in a server

**Expected behavior**
once you exit a server with server list disabled it should know that you left said serve

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: windows 10
 - JAVA Version: 8
 - Mod Version: 1.1
 - Discord Version: latest
 - Minecraft Version: 1.16.3
 - Fabric Version: 0.10.1+build.209

**Comment by hypherionmc** [comment]
Hmmm, okay it relies on those screens being opened to trigger certain events. I will add a work around for it

**Comment by hypherionmc** [comment]
Would you mind giving this build a try please? It should automatically update your config file to support the new event, but please make a backup of your current config file just in case.

https://ci.hypherionmc.me/job/Simple%20RPC/job/1.16.3%20(Fabric)/7/artifact/build/libs/simple-rpc-1.16.3-1.2.7.jar

**Comment by hypherionmc** [comment]
Would you mind please letting me know if you've had a chance to test the above build yet and if it solves your issue, so I can push it to release

**Comment by DaddySpin** [comment]
Ah sorry! was offline for a few days. will try to give it a test sometime.

**Comment by hypherionmc** [comment]
No problem and thank you :)

**Comment by hypherionmc** [comment]
Fixed in new release
