### ISSUE TITLE
[BUG] Time enlapsed resets when a world is loaded

### ISSUE THREAD

**Issue by Oondanomala** [hypherionmc/simple-rpc-public#20]
**Describe the bug**
Not sure if this is intended or not, but the time enlapsed resets when loading a world.
If this is intended it would be nice to add an option to disable it.

**To Reproduce**
1. Load a wold
2. Notice the timer resets to 0

**Expected behavior**
The timer doesn't reset

**Versions:**
 - OS: Windows 10
 - JAVA Version: 17.0.1 x64
 - Mod Version: 2.5.1 Beta
 - Discord Version: Stable 106905
 - Minecraft Version: 1.18
 - Fabric Version: 0.12.8

**Additional context**
Doesn't reset when leaving a world

**Comment by hypherionmc** [comment]
This one isn't really a bug. Originally the mod was coded to reset the timer each time a section is loaded, but in recent updates that got changed and only the world one remained, but I agree with you that the timer should not be reset.

I saw you reported another issue, so I'll add all the fixes to the next update

**Comment by hypherionmc** [comment]
If you don't mind, can you please test with this build. This should fix both issues you reported: https://ci.firstdarkdev.xyz/job/Simple%20RPC/job/Fabric/job/1.18%20(Fabric)/16/artifact/build/libs/simple-rpc-1.18-2.6-dev-16-fabric.jar

**Comment by Oondanomala** [comment]
It does fix both issues!

**Comment by hypherionmc** [comment]
Release 2.6 is out with both bug fixes. Curse is just approving the last of the files. Thanks for reporting and for your feedback
