### ISSUE TITLE
[BUG] PLACEHOLDERS NOT WORKING ON DIRECT CONNECTION.

### ISSUE THREAD

**Issue by MetTheCarrot** [hypherionmc/simple-rpc-public#24]
**Describe the bug**
From the Multiplayer window, when I enter a server in the direct connection button, the placeholders stop working, while if I log in using Join Server, they work.

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'Direct Connection'
4. Put any IP from any server.
5. Click on 'Join Server'
7. See error

**Expected behavior**
A clear and concise description of what you expected to happen:
I expected it to work the same way by entering from the Join to server button, it is the same function

**Screenshots**
https://imgur.com/a/F4R02kf

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 64 Bits
 - JAVA Version: 1.17.1 (Java 16)
 - Mod Version: 2.7.1
 - Discord Version: Stable 115093 (f7a2ab2)
 - Minecraft Version: 1.17.1
 - Forge/Fabric Version: fabric-loader-0.13.1-1.17.1

**Additional context**

**Comment by hypherionmc** [comment]
Release 2.7.2 fixes this issue :)
