### ISSUE TITLE
[BUG] Game crashes on Fabric 1.18.2 after entering a World.

### ISSUE THREAD

**Issue by OhaDerErste** [hypherionmc/simple-rpc-public#25]
**Describe the bug**

**To Reproduce**
1. Open a World

**Expected behavior**
The world should open

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Arch Linux x86
 - JAVA Version: 17.0.1
 - Mod Version:2.7.2
 - Discord Version:Canary 117007 (ab5065d)
 - Minecraft Version:1.18.2
 - Forge/Fabric Version: Fabric 0.13.3-1.18.2

**Additional context**
Crash report:
https://paste.horlboge.de/lawuzoficu.http

**Comment by hypherionmc** [comment]
Huh.... I knew 1.18.2 broke some stuff, but never imagined it would affect this mod too.... I'll release a fix later this evening

**Comment by OhaDerErste** [comment]
Works, thank you!

**Comment by hypherionmc** [comment]
Awesome. Pushing release to Curseforge :)
