### ISSUE TITLE
Hiding default Minecraft Rich Presence with custom App

### ISSUE THREAD

**Issue by JustAlittleWolf** [hypherionmc/simple-rpc-public#26]
It is very annoying that with the built in custom Rich Presence it hides the default **Playing Minecraft** dialogue in the user popout but when I made my own app it doesn't hide it anymore.

With Custom Application
![image](https://user-images.githubusercontent.com/54244277/158258653-ee9fed22-b32b-4c9c-bac6-575292fc5c33.png)

Without Custom Application (using ClientID = 762726289341677668)
![image](https://user-images.githubusercontent.com/54244277/158258748-add11b57-71a6-4ee1-b278-2ddf153d3d22.png)

**Comment by hypherionmc** [comment]
That's got nothing to do with the mod. That is a glitch with discord sometimes detecting Minecraft (the one you see below the rich presence) and other times not

**Comment by JustAlittleWolf** [comment]
> That's got nothing to do with the mod. That is a glitch with discord sometimes detecting Minecraft (the one you see below the rich presence) and other times not

This is always the case when switching between the two, it always hides the default minecraft rpc on your application and always shows it on a different application. Does it have something to do with the Application then?

**Comment by JustAlittleWolf** [comment]
> What I suspect is, because the name of the default included app is Minecraft, it just hides the game detection, thinking it's actually Minecraft showing the rpc status.

This was very helpful, thank you. I have now changed the application name to `Minecraft` instead of `Minecraft Fabric` and it doesn't show the normal playing minecraft anymore.
