### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaTiTV** [hypherionmc/simple-rpc-public#28]
The placeholders are not replaced

![image](https://user-images.githubusercontent.com/75247188/160907070-57e05801-656d-469d-a6fc-800a4e2f8930.png)

 - OS: Windows 11
 - JAVA Version: jdk-17.0.1
 - Mod Version: 2.7.3
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: Fabric Loder 0.13.3 / Fabric API 0.48.0+1.18.2

**Comment by hypherionmc** [comment]
Did you join via direct connection? If so, can you try connecting through a normal saved connection to check if it works?

Also the server you're running on, does it run any special software like Waterfall or bungeecord, or is it just plain fabric?

**Comment by JaTiTV** [comment]
Is network with cloudnet, stored as well as direct connection the same.

On another server it works but there is 99 displayed although 3 are online because they use the BungeeTabListPlus

**Comment by JaTiTV** [comment]
yes I can do tonight when I am at the pc
