### ISSUE TITLE
[BUG] Crash at launch

### ISSUE THREAD

**Issue by Leeo97one** [hypherionmc/simple-rpc-public#3]
**Describe the bug**
The game crashes on launch when the mod is loaded.

**To Reproduce**
1. Install the mod
2. Launch the game

**Expected behavior**
The game loads successfully.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Arch Linux (5.9.6-zen1-1-zen)
 - JAVA Version: openjdk version "1.8.0_265"
 - Mod Version: 1.16.3-1.2-fabric
 - Discord Version: Stable 71447 (29091ef) Host 0.0.12
 - Minecraft Version: 1.16.3
 - Fabric Version: 0.10.6+build.214

**Additional context**
[crash-2020-11-12_12.17.08-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/5530269/crash-2020-11-12_12.17.08-client.txt)

**Comment by hypherionmc** [comment]
Hi there

Hmm interesting crash. I haven't actually tested the mod on a linux installation, but I will try it out. If I can reproduce I will add a fix for it.

Just to be completely sure, you do have the Fabric API mod installed?

**Comment by Leeo97one** [comment]
> Just to be completely sure, you do have the Fabric API mod installed?

Yes, as stated in the crash report (Fabric API 0.25.0+build.415-1.16).

**Comment by hypherionmc** [comment]
Okay so a quick check (don't have the Code used by my Discord API ATM), reveals that it's a library issue. I will do a fix for it. Will you be willing to give a dev build a test before I push a release?

**Comment by Leeo97one** [comment]
> Will you be willing to give a dev build a test before I push a release?

Sure!

**Comment by hypherionmc** [comment]
I will do the fix when I get home and link the dev build for you

**Comment by hypherionmc** [comment]
You can give this build a test: https://ci.hypherionmc.me/job/Simple%20RPC/job/1.16.3%20(Fabric)/11/artifact/build/libs/simple-rpc-1.16.3-1.3.11.jar

**Comment by Leeo97one** [comment]
It seems to work fine 👌🏽

**Comment by Leeo97one** [comment]
Also, it seems to work fine with MC 1.16.4 if you just change the `fabric.mod.json` file to allow it.

**Comment by hypherionmc** [comment]
Awesome. Thanks for the feedback. The release should be on curse shortly (supporting 1.16.3 and 1.16.4)

**Comment by hypherionmc** [comment]
Release is out. Thanks for reporting :)
