### ISSUE TITLE
[Suggestion] Server address instead of stored server name

### ISSUE THREAD

**Issue by JaTiTV** [hypherionmc/simple-rpc-public#30]
Could you add this, so that not the name is displayed as you have saved it, but the address with which you come to the server?

![image](https://user-images.githubusercontent.com/75247188/162643061-10ae2987-077f-43d0-b914-a773b7a6b13f.png)

**Comment by hypherionmc** [comment]
You can use the `%serverip%` variable for that. It will show the IP/Web address you used to connect to the server with. Alternatively, you can define a [custom server entry](https://readme.firstdarkdev.xyz/simple-rpc/server-entries/) to override all the info based on the connection address
