### ISSUE TITLE
The options menu for the mod is not accessible

### ISSUE THREAD

**Issue by Musta-VG** [hypherionmc/simple-rpc-public#32]
When I first used it, it was shown on the settings. But after a while it disappeared

**Screenshots**
![Screenshot_159](https://user-images.githubusercontent.com/77793061/165189880-05f82698-daed-4f57-8741-b496dd509187.png)

Versions:
 - OS: Windows10
 - JAVA Version: 16(Or 8, I am still confused)
 - Mod Version: 3.0.0
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: 0.47.10(I think)

**Comment by hypherionmc** [comment]
Huh. That's weird 🤔. Did you maybe remove Cloth Config? Also, you're JAVA version for 1.18.2 should be 17 😄

**Comment by Musta-VG** [comment]
> 

well as I said, I am still confused about it

**Comment by hypherionmc** [comment]
Same here. What changed between the last time it worked and now? Or did it just stop working without you doing anything to the setup?

**Comment by Musta-VG** [comment]
> Same here. What changed between the last time it worked and now? Or did it just stop working without you doing anything to the setup?

Nothing changed, just the button suddenly disappearing

**Comment by Musta-VG** [comment]
> > Same here. What changed between the last time it worked and now? Or did it just stop working without you doing anything to the setup?
> 
> Nothing changed, just the button suddenly disappearing

So after a little of digging, I think I found out why. Maybe it automaticly installed the wrong version of the cloth called "cloth-basic-math" I am trying to remove it, but can't. so that may be why it doesn't allow cloth config to work

**Comment by hypherionmc** [comment]
Hey. Any feedback on this? Did you get it working again?

**Comment by hypherionmc** [comment]
Can you send me a copy of the modlist or modpack this happened in so I can test on my side as well, so we can push out a fix. I suspect it's a mod conflict
