### ISSUE TITLE
Betterdiscord incompatibility? 

### ISSUE THREAD

**Issue by owosoup** [hypherionmc/simple-rpc-public#34]
**Describe the bug**
discord doesn't pick up the rich presence and doesn't show it on my profile.

**To Reproduce**
1. Use betterdiscord???

**Expected behavior**
I thought enabling and disabling it would recover it but no, nothing

**Screenshots**
![2022-05-27_19 24 35](https://user-images.githubusercontent.com/95828007/170760864-77ef05ab-5b80-432e-8f23-259d1aacb799.png)
![Capture d’écran 2022-05-27 192907](https://user-images.githubusercontent.com/95828007/170761023-345581a2-d6d2-4c32-bb22-cce157429c44.jpg)

**Versions:**
 - OS: Windows 10 64-Bit 
 - JAVA Version: Javaw / 17.0.1
 - Mod Version: 3.0.1
 - Discord Version: BetterDiscord 1.5.3
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: Fabric loader 0.14.5

**Additional context**
I don't know what happened honestly, it just stopped working, so I thought updating the mod to the latest version would fix it, but it didn't. I don't know what were the conditions that met which led to discord not reacting.

**Comment by owosoup** [comment]
> It shouldn't be incompatible, but I've never tested this myself as better discord refuses to work on my system. What I do know is that Better Discord likes to launch discord in Admin mode, which makes it impossible for the mod to communicate with it.
> 
> My first step would be to check if discord is running in admin mode (close and restart discord and see if it asks for permission to run). If it does not, the next step would be to ensure game activity is still enabled

![image](https://user-images.githubusercontent.com/95828007/170763353-49ce6ff3-bdc1-43ce-9f5b-3987b7fa1881.png)
activity status is on, and upon launch, no requests are made for administrator

**Comment by hypherionmc** [comment]
Odd. Did it ever work before on Better Discord, and if so, do you remember what was the last working version?

**Comment by owosoup** [comment]
> Odd. Did it ever work before on Better Discord, and if so, do you remember what was the last working version?

I remember the version using a different button for the config screen, it being placed below the 'save and quit" button.
it also only had two options, being enable/disable simple rpc, and debug logging
the button had 'simple rpc' displayed on it, or something of the like.

**Comment by owosoup** [comment]
> 

tried 2.7.3, the version I recall using, and it no longer works either.
![2022-05-27_19 56 00](https://user-images.githubusercontent.com/95828007/170765203-0b131bdc-2634-4b72-b288-3c94cdc81844.png)

**Comment by owosoup** [comment]
![image](https://user-images.githubusercontent.com/95828007/170820260-7f4e5400-d4b6-42ca-9adc-165d4f62a716.png)
for some reason after a restart it started working again?
it probably was on discord's side, since I restarted the instance many times without results.
If it happens to you, reboot!
