### ISSUE TITLE
[BUG]Crashing when joining World

### ISSUE THREAD

**Issue by LoganOfDoom** [hypherionmc/simple-rpc-public#35]
**Describe the bug**
Crashing when joining World

**To Reproduce**
Start Minecraft with the mod and join a world

**Expected behavior**
Not crashing

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10
 - JAVA Version: 17.0.3 64bit
 - Mod Version: 22w15a-3.0.1
 - Discord Version: Stable 131246 (fed1161)
 - Minecraft Version: 1.19
 - Forge/Fabric Version: fabric: 0.14.6-1.19
[crash-2022-06-09_16.10.06-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/8871208/crash-2022-06-09_16.10.06-client.txt)

**Comment by hypherionmc** [comment]
Thanks for reporting. It looks like all mods built against the snapshot of 1.19 is not compatible with release of 1.19.... We're busy getting ready to properly port to 1.19, so a proper release should be out some time this weekend

**Comment by hypherionmc** [comment]
A proper release is out now on Curse and Modrinth :)
