### ISSUE TITLE
[Suggestion] A new variable that replaces itself with the player UUID

### ISSUE THREAD

**Issue by ZenialDev** [hypherionmc/simple-rpc-public#36]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem

**Describe the solution you'd like**
Add a new variable that replaces itself with the player UUID so that it can be used with Crafatar (or other image APIs) for presence image keys
Ex: `smallImageKey = "https://crafatar.com/avatars/%playeruuid%.png"`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hypherionmc** [comment]
We do have a built in variable that allows you to use the player head as an image. 

`%playerhead%`. I could expose more options to change what type of skin is returned from the API

**Comment by SkiddledGitHub** [comment]
I couldn't really figure out how to use `%playerhead%`, could you explain how it works?

**Comment by hypherionmc** [comment]
You place it inside your config, in one of the `imageKeys`, and it automatically pulls the player head from gravatar. So basically, this: `https://crafatar.com/avatars/%playeruuid%.png` but it's all done internally so you don't need to include the URL as well

**Comment by SkiddledGitHub** [comment]
Pretty sure I did it right but it doesn't work for some reason
https://www.toptal.com/developers/hastebin/raw/iqocapiqay
Verified it with TOML Lint as well

**Comment by hypherionmc** [comment]
Hmmm sounds like a bug then. Which Game Version and Mod version are you using?

**Comment by SkiddledGitHub** [comment]
I am using Minecraft 1.18.2 with Fabric version 0.14.7
Mod version is 3.0.1

**Comment by SkiddledGitHub** [comment]
Thank you very much c:

**Comment by SkiddledGitHub** [comment]
> Let me get one of our devs to check this out. Definitely sounds like it's not returning the url format correctly internally

I've just realized that if I join a world / server / realms the %playerhead% variables returns the correct value
Not in the title screen or anywhere else

**Comment by hypherionmc** [comment]
Huh. Thanks for the feedback. I think I know what the problem is.... I never allowed that variable to be used everywhere

**Comment by SkiddledGitHub** [comment]
> I never allowed that variable to be used everywhere
Is there a specific reason why?

**Comment by hypherionmc** [comment]
No reason, just an oversight on my part. Actually this is a bug... It's pulling the UUID of the player, from the actual player instead of the game profile, which means, outside of a world, the player would be null and the UUID won't resolve
