### ISSUE TITLE
[BUG] Player count placeholder no longer supported?

### ISSUE THREAD

**Issue by Just-Ju** [hypherionmc/simple-rpc-public#37]
**Describe the bug**
I have the %players% placeholder as my discord statues and it displayed the number correctly however after updating the mod its shows as %players% and not the number of players online

**To Reproduce**
Just use %players% ad the placeholder.

**Expected behavior**
To have the number of players displayed and not %players%

**Screenshots**
![image](https://user-images.githubusercontent.com/84942439/177036041-dda7924d-9bff-4c0b-a471-14083d7bf0da.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS:
 - JAVA Version: 18
 - Mod Version: 1.19-3.0.2
 - Discord Version: 126.17
 - Minecraft Version: 1.19
 - Forge/Fabric Version: fabric

**Additional context**

**Comment by hypherionmc** [comment]
Hey. No it should still be working. I'll test this on my side later today.
