### ISSUE TITLE
[BUG] dysfunctional client after adding custom buttons?

### ISSUE THREAD

**Issue by squoshi** [hypherionmc/simple-rpc-public#38]
**Describe the bug**
`[Simple RPC/]: Could not load config file. Something unknown went wrong`

**To Reproduce**
1. Replace buttons = [] with `[[main_menu.buttons]] and so-forth`
2. Try to run Minecraft
3. Look at Discord status

**Expected behavior**
Use of custom application with added buttons

**Versions:**
 - OS: Windows 10
 - JAVA Version: 17
 - Mod Version: 3.0.1
 - Discord Version: Stable 133852 (ad1408e)
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: 40.1.54

**Comment by hypherionmc** [comment]
Can you send me a copy of the config file where this happens?

**Comment by hypherionmc** [comment]
Feature still works as intended in latest versions. Without seeing the config where this happens, the issue cannot be reproduced
