### ISSUE TITLE
Add replaymod support

### ISSUE THREAD

**Issue by 1Euro7Cent** [hypherionmc/simple-rpc-public#40]
**Is your feature request related to a problem? Please describe.**
When I am editing/setting paths for the replaymod RPC shows that I am playing in the world. Or when I am rendering the video.

**Describe the solution you'd like**
Add an RPC category for replaymod and change description accordingly:
+ when editing camera paths ect.
+ rendering the clips
+ maybe when I am in the replay viewer too

**Describe alternatives you've considered**
**Additional context**

**Comment by hypherionmc** [comment]
Hi there.

Do you have a link for the mod? I'll see what I can do :)

**Comment by 1Euro7Cent** [comment]
https://www.replaymod.com for making renders with sodium you need to use one of the sodium versions from them

**Comment by hypherionmc** [comment]
Thank you. Forgot to reply to this. I'll add support in the next version

**Comment by hypherionmc** [comment]
Hey. Just to update, I haven't forgotten about this. I haven't been active with development lately because of IRL things. 

I'm doing an update for the mod this week, and will be including support for this as well

**Comment by hypherionmc** [comment]
Added support for the Replay Viewer screen, editor screen and the render screen. Couldn't get an image of the Render Rich Presence because I don't have the mod fully set up

![image](https://user-images.githubusercontent.com/63595580/197419146-4fac4e05-81d4-482e-88e3-5808ae888674.png)
![image](https://user-images.githubusercontent.com/63595580/197419167-c5f04853-7ce1-4248-bc7a-c89ee7b88ae7.png)

**Comment by 1Euro7Cent** [comment]
When rendering a video is there an ability to see the current frames like: `frame x of y pp%`

**Comment by hypherionmc** [comment]
I'll see if I can pull that data from their gui and into a variable. Will keep you updated

**Comment by hypherionmc** [comment]
Alright. Got everything implemented, aside from FPS. They don't expose a way to get that

Will give you a chance to test before we release this, as I haven't been able to test it fully (as mentioned before)

**Comment by 1Euro7Cent** [comment]
I would love to test it. But the problem is that i cannot fo that for this and next week. If the next release date is after that time i would test is

**Comment by hypherionmc** [comment]
No worries. I'll see to test it on my side as well. I'm finalizing things for release, so it will be very soon

**Comment by hypherionmc** [comment]
Feature was released with 3.2.0
