### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StuttR** [hypherionmc/simple-rpc-public#41]
**Describe the bug**
Discord will not display on profile custom presence, even with double checking if the code was correct, checking in-game and in the editor, reading the troubleshooting guide, everything looked fine

**To Reproduce**
None

**Expected behavior**
Display custom presence to discord

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows
 - JAVA Version: 17.0.4
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: 40.1.57

**Additional context**
The .toml editor software shows that it's connected to the discord app, but the discord app won't display anything on my profile

**Comment by hypherionmc** [comment]
Did you get this working at all? Most common issues on Windows are Running discord as Admin, or the applicationID is incorrect
