### ISSUE TITLE
[BUG] Extensive Testing, Dimension Overrides Not Working

### ISSUE THREAD

**Issue by Camawama** [hypherionmc/simple-rpc-public#42]
**Describe the bug**
I spent quite a bit loading my modpack, noticing it wasn't displayed correctly, closing the modpack, tweaking the config, re-opening the modpack, etc. I came to the conclusion that it is, in fact, a bug, and I am not losing my mind.

**To Reproduce**
1. Set a custom dimension override for a mod
2. Open the world and teleport to the specific dimension
3. Notice that it isn't being displayed correctly on Discord

**Expected behavior**
In the CONFIG, it is set to say "%player% is Vibing on Mars" but it instead says  "Currently in the Mars"

**Screenshots**
![InGame](https://user-images.githubusercontent.com/43620900/183281942-79e7b2b4-d667-4a1e-b6fa-0c07819148a0.png)
![ConfigEditor](https://user-images.githubusercontent.com/43620900/183282098-ebdd73bc-a8c2-4302-b200-70512644dfd8.png)

![DiscordDisplay](https://user-images.githubusercontent.com/43620900/183281944-4d7ac977-5ef9-4931-8897-8432ee2a5070.png)
![WhatisActuallyDisplayed](https://user-images.githubusercontent.com/43620900/183281945-8d23ab02-a0c5-400b-8bac-1b930bddb1cf.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 Pro
 - JAVA Version: Java version "17.0.1" 2021-10-19 LTS
 - Mod Version: simple-rpc-1.18.2-3.1.1.jar
 - Discord Version: Stable 140355 (cd30e81)
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: Forge 40.1.69

**Additional context**
This mod has been the easiest and best to use by far. I really hope someone can explain what I'm doing wrong or fix the bug. Thank you!

**Comment by hypherionmc** [comment]
Hey there. Thanks for your report. Can you send me a copy of your config? 

I think it may be our editor not properly saving stuff. I noticed this more and more, but people aren't reporting it

**Comment by Camawama** [comment]
GitHub doesn't support that file format. Here is a link to my CONFIG on Google Drive.

https://drive.google.com/file/d/1vz71Ev_HL37J9cObX-I0oWWdf_l-poTv/view?usp=sharing

**Comment by hypherionmc** [comment]
Thanks. Your config looks correct. Let me do some testing on my side as well. I'll keep you updated

**Comment by Camawama** [comment]
Thank you. I will be back in about 6 hours. Sleep is important lol.

**Comment by Camawama** [comment]
I am also now noticing that the IMAGE only shows up on MOBILE DISCORD
![image](https://user-images.githubusercontent.com/43620900/183311595-8bc21fcf-f832-444b-8fee-318cfa1e292e.png)

**Comment by hypherionmc** [comment]
> I am also now noticing that the IMAGE only shows up on MOBILE DISCORD ![image](https://user-images.githubusercontent.com/43620900/183311595-8bc21fcf-f832-444b-8fee-318cfa1e292e.png)

You have image key `overworld` specified for the overworld override, but you don't have an image on your app matching that.

![image](https://user-images.githubusercontent.com/63595580/183312342-9ca5cad7-0349-452d-b2bf-e07618480005.png)

**Comment by hypherionmc** [comment]
Alright, so this is definitely a bug. I was returning the incorrect string to be checked against.

So to replicate, remove `beyond_earth:` from your overrides, and it will work.

Additionally, this build has a fix for the problem, so you can use it without changing anything. You can use it for testing so long, until I release the fix
https://ci.firstdarkdev.xyz/job/Simple%20RPC%20Modern/job/1.18.2/10/artifact/artifacts/simple-rpc-1.18.2-3.1.10d.jar

**Comment by Camawama** [comment]
Ohh, the image things got reset when config reset itself on me, lol.

I am going to use the version currently out to the public so that when I publish the pack, it doesn't deny it on CurseForge. Hopefully, the new update will be out soon. Glad I was able to help find an issue!

**Comment by hypherionmc** [comment]
Sorry, I know it's been a while. Been busy with IRL things. I'm doing a release this week with the fix included.

**Comment by Camawama** [comment]
That's great news!

**Comment by hypherionmc** [comment]
Fixed with release 3.2.0
