### ISSUE TITLE
[Suggestion] Image Pool

### ISSUE THREAD

**Issue by Camawama** [hypherionmc/simple-rpc-public#44]
**Is your feature request related to a problem? Please describe.**
There is no problem, only an idea!

**Describe the solution you'd like**
An image pool where a random image can be chosen instead of a specific one

**Describe alternatives you've considered**
I haven't thought of any alternative solution. This is simply a Feature Request.

**Additional context**
Just thought I'd add this here. Your mod is amazing and the config editor is super clean and simple to use. By far the best one out there!

**Comment by hypherionmc** [comment]
Can be done. Should just be a simple config tweak

**Comment by Camawama** [comment]
I should have been more specific.

If a player is in, say, the Twilight Forest. There could be 5 different images that have a chance of being displayed. I can take cool screenshots in game of the Twilight Forest and put them in that image pool for the specific dimension.

**Comment by hypherionmc** [comment]
Sorry for the delay on my side. Been busy with IRL things. I can add support for this. The new layout will basically be 'largeImageKey = ["key1", "key2", "key3"]`

I'm doing a release this week and it will include this feature

**Comment by hypherionmc** [comment]
Update, got this implemented. 

The new format is `largeImageKey = ["mclogonew", "mclogo", "bricks", "chicken"]`. This will select the images from the list at random during updates

Once I close this issue, it means a release was made with this feature included.

**Comment by hypherionmc** [comment]
Feature was released with version 3.2.0. Works as described above
