### ISSUE TITLE
[BUG] Multiplayers variables doesnt work

### ISSUE THREAD

**Issue by Ryuushen** [hypherionmc/simple-rpc-public#46]
The server override works fine however %players% and %maxplayers% and other multiplayers variables doesn't show anything but plaintext

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11
 - JAVA Version: Java 17
 - Mod Version: 1.18.2
 - Discord Version: Stable 149549
 - Minecraft Version: 1.18.2
 - Forge/Fabric Version: Fabric

**Comment by Ryuushen** [comment]
Yessir that is correctThat is correct here is a screenhot for it
![Discord_wVnUCa4FyP](https://user-images.githubusercontent.com/24853902/192972224-240ecb46-5c1a-4a78-a6e3-344c190466a7.png)

**Comment by hypherionmc** [comment]
Hey. Sorry, I have not forgotten about this. Just been really busy with IRL stuff. I am doing an update for this mod this week and will investigate this/see how we can do it better

**Comment by Ryuushen** [comment]
Ay man nothing to say sorry about. It's understandable, I'm grateful you're doing this for free. Take your time, I'll wait for update :)

**Comment by CaliberZenith** [comment]
@Ryuushen is it possible to ask for the Fabric version you used? Just so I can test for things?

**Comment by Ryuushen** [comment]
> @Ryuushen is it possible to ask for the Fabric version you used? Just so I can test for things?

Yes I used fabric 1.18.2

**Comment by CaliberZenith** [comment]
Oh wait. Nevermind I'm dumb. I forgot there was only 1 version in 1.18.2 kek
anyway, gonna test in a bit. Thank

**Comment by CaliberZenith** [comment]
Can you post the log when you encountered this bug? @Ryuushen ? I tried to replicate it but it doesn't seem to happen to me.

**Comment by Ryuushen** [comment]
> Can you post the log when you encountered this bug? @Ryuushen ? I tried to replicate it but it doesn't seem to happen to me.

Interesting. I do use it with 150+ other mods might be some conflict. Ill check it tomorrow and get back to you. Thank you for looking over it

**Comment by Ryuushen** [comment]
> Can you post the log when you encountered this bug? @Ryuushen ? I tried to replicate it but it doesn't seem to happen to me.

Though im quite new so could you explain to me how would i get log for this?

**Comment by CaliberZenith** [comment]
C:\Users\<User>\AppData\Roaming\.minecraft\logs

If I'm correct.

**Comment by hypherionmc** [comment]
So looks like this was an actual bug. Somewhere between updates I left out a crucial line of code, that caused the config to not reload when changes are made, or to "live" update basically
