### ISSUE TITLE
[Suggestion] Variable for Modpack Version

### ISSUE THREAD

**Issue by AftDawn** [hypherionmc/simple-rpc-public#49]
**Is your feature request related to a problem? Please describe.**
At the moment i'm having to update the modpack version in all of the places that they appear at the moment, and it's quite annoying

**Describe the solution you'd like**
Have something like %modpack_version% or something similar, this could even extend to custom variables!

**Describe alternatives you've considered**
Maybe if you don't want custom variables, maybe just a small handful of predetermined variables that can be controlled?

**Comment by hypherionmc** [comment]
That's definitely a useful feature.

Maybe I can include the possibility to define your own variables. So that the user can add variables with fixed values, like the modpack name/version or support links etc

**Comment by hypherionmc** [comment]
With the upcoming release, you will be able to do this:

![image](https://user-images.githubusercontent.com/63595580/200895201-35cf3258-b3c9-4db3-bd82-90bf2e73e8f1.png)

Which will show as 

![image](https://user-images.githubusercontent.com/63595580/200895259-6e668c96-79f6-49f4-b28f-88a0816f4060.png)

**Comment by hypherionmc** [comment]
You can define as many as you want, and they work inside buttons/imagekeys too.

So you can now define a custom variable for duplicate data, and simply use the variable instead

**Comment by hypherionmc** [comment]
Feature was released with Version 3.2.0.

https://srpc.fdd-docs.com/custom-variables/
