### ISSUE TITLE
[BUG] Minecraft Version is incorrect

### ISSUE THREAD

**Issue by supsm** [hypherionmc/simple-rpc-public#5]
**Describe the bug**
The `%mcver%` isn't listing the correct version

**To Reproduce**
1. Open minecraft with simple rpc 1.4.1 in mc version 1.16.4
2. Go to Discord
3. Click on your profile
4. Hover over the Minecraft logo (I've changed the icon in the screenshot)
5. See error

**Expected behavior**
It should say Minecraft 1.16.4 instead of Minecraft 1.16.3

**Screenshots**
![image](https://user-images.githubusercontent.com/60897356/103164146-401d0700-47bc-11eb-9a94-c6070f3d062a.png)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 10 version 20H2
 - JAVA Version: OpenJDK 1.8.0_275
 - Mod Version: 1.4.1 Fabric
 - Discord Version: 0.0.309?
 - Minecraft Version: 1.16.4
 - Fabric Version: Fabric Loader 0.10.8, Fabric API 0.25.1

**Additional context**

**Comment by hypherionmc** [comment]
Hi. Thanks for reporting. It has been fixed in an upcoming release
