### ISSUE TITLE
Crash upon loading a world with 1.19.3

### ISSUE THREAD

**Issue by mmkthecoolest** [hypherionmc/simple-rpc-public#50]
**Describe the bug**
Minecraft 1.19.3 crashes when loading a world with SimpleRPC 3.2.0, PrismLauncher 5.2, Fabric API 0.68.1+1.19.3 and Fabric Loader 0.14.11

**To Reproduce**
1. Launch the game with only SimpleRPC and Fabric API enabled
2. Select a single-player world to load

**Expected behavior**
World should load with no problems

**Versions:**
 - OS: Windows 10
 - JAVA Version: Amazon Corretto 17.0.5
 - Mod Version: 3.2.0
 - Discord Version: Stable 162835 (ec38a0d)
 - Minecraft Version: 1.19.3
 - Fabric API Version: 0.68.1+1.19.3
 - Fabric Loader Version: 0.14.11

**Logs:** https://mclo.gs/u1R1k1V

**Comment by hypherionmc** [comment]
Urgh seriously Mojang.... WHY DO YOU ALWAYS DO THIS.

I'll have to release an update for this. Thanka for reporting the error

**Comment by hypherionmc** [comment]
Issue has been fixed in release 3.2.1.

It's live on Modrinth, still pending on Curseforge
