### ISSUE TITLE
[Suggestion] Prism Launcher Support

### ISSUE THREAD

**Issue by snoweuph** [hypherionmc/simple-rpc-public#52]
**Is your feature request related to a problem? Please describe.**
Prism Luancher gets shown as Multimc

**Describe the solution you'd like**
adding support for Prism MC

**Additional context**
MultiMC did shit and got the fork called Poly MC, Poly MC did shit and got fork Prism MC.

**Comment by CDAGaming** [comment]
Personally speaking, this is more of a special case then anything else.
Prism is inherently a fork of MultiMC, so they use the same base logic that Simple DRPC uses to identify it as MultiMC

In simple terms: I dont think there is is much, if anything, that Hypher can add to seperate the two. Plus it also brings into question: There are 100's of other named forks for MultiMC, what about them? (Adding integration for one fork opens up quite a can of worms pretty much)

**Comment by hypherionmc** [comment]
I tried to add support as best I could in the latest version. I do not use Prism myself, so you are welcome to test it and let me know if it works. If not, please re-open this ticket

**Comment by snoweuph** [comment]
yes, I will test it when I have time, thx
