### ISSUE TITLE
[BUG] Client crash on 1.16.5

### ISSUE THREAD

**Issue by HollishKid** [hypherionmc/simple-rpc-public#53]
**Describe the bug**
When loading into a world, the client will crash.

**To Reproduce**
Simply load a world with the mod installed.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows10 (both server and client, for testing)
 - JAVA Version: 1.8.0_51
 - Mod Version: 3.2.0
 - Discord Version: Stable 171621 (b20d67a)
 - Minecraft Version: 1.16.5
 - Forge/Fabric Version: Forge: 36.2.39

**Additional context**
Full crash report here: https://pastebin.com/gUCnXvu6

**Comment by hypherionmc** [comment]
Hey. Thanks for the report. I'll look into this and get back to you

**Comment by hypherionmc** [comment]
Okay, so looking at the code, this seems to be a config issue. Can you post your config as well please?

**Comment by HollishKid** [comment]
Sorry, I did not think about posting it in the first place.
This is the simple-rpc.toml: https://pastebin.com/PGskbLSM
The server-entries.toml if default/unmodified.

**Comment by hypherionmc** [comment]
Ah, there is the problem.

Replace all copies of `[[dimension_overrides.buttons]]` with `[[dimension_overrides.dimensions.buttons]]` and it should work

**Comment by HollishKid** [comment]
That worked like a charm. Thank you very much for your help!
