### ISSUE TITLE
Button is discord status doesn't refresh values without game restart

### ISSUE THREAD

**Issue by Edeq79** [hypherionmc/simple-rpc-public#54]
**Describe the bug**
I made a button in my discord status that reads multiplayer server name with %server% command and searches it in google by running this URL: https://www.google.com/search?q=%server%
And this button doesn't read new value when I join other server.

There is probably sth wrong with %server% or button caching.

**To Reproduce**
1. Join a random multiplayer server
2. Quit to game menu
3. Join another random multiplayer server
4. Look at button in your discord status

**Expected behavior**
Button in discord status displays information about first server that was joined after launching the game when you are on a different server

**Screenshots**
This is how my button is defined for multiplayer status:
![image](https://user-images.githubusercontent.com/125321058/222985843-e901ffe4-a115-45d4-bcb2-be20d8109dc5.png)

This is displayed when I join the server for the first time after game launch (everything fine here):
![image](https://user-images.githubusercontent.com/125321058/222985952-689199a5-b147-4a48-8884-8724fb1de3e7.png)

This is displayed when I join other server without game restart:
![image](https://user-images.githubusercontent.com/125321058/222985411-555f04be-1c7e-4cee-ba57-ac097add0572.png)

And link stays the same like from the first server:
![image](https://user-images.githubusercontent.com/125321058/222987151-6062f633-c2b4-4cf3-8ad0-14b92aeea6c1.png)

 - OS: Windows 10
 - Mod Version: 3.2.1
 - Fabric Version: 1.19.2
 
Also little suggestion: add in mod documentation a page with some creative examples of setting up poles/commands of this mod (like mine) :D
 
 PLEASE ADD FIX TO 1.19.2 VERSION OF THE MOD TOO BECUASE MANY PPL STILL USE IT

**Comment by hypherionmc** [comment]
Hey. Thanks for the report.

Yes there seems to be some issues with button caching. We've got a similar report on discord, but it was related to buttons overall, not just multiplayer.

The mod is due for an update again, so I'll take a look at this.


As for adding in-game documentation, it was considered before, but our documentation changes way too much. Currently we use an automated system where the documentation is updated on github, and automatically deployed to our docs. If we add in-game docs, we will have to add some sort of "sync" system for that as well. 

Our docs use a MARKDOWN format (similar to github), with some custom stuff supported by our docs platform. I do not know of any mods that can support this 1:1 or even partially, so it would just add a whole other level of complications to keeping the mod updated.


Later this year we will start work on Version 4 of the mod, which will basically be a complete rewrite to clean up the codebase and in general improve the mod. So if at that time there is something we can use for that, it will be added.


And finally, yes 1.19.2 will still be updated until such time that a separate 1.19.3 version is required. We choose to drop support for a version based on download counts, the amount of effort required to keep it updated and just general support for that version overall. So 1.16.5 and 1.17 is likely to be dropped way before 1.18+

**Comment by hypherionmc** [comment]
Issue was fixed with release 3.2.2
