### ISSUE TITLE
[BUG] Image Does Not Change In Bottom Left Corner

### ISSUE THREAD

**Issue by PolyframeX** [hypherionmc/simple-rpc-public#55]
**Describe the bug**
When Settings A Custom Icon, It Still Uses The Base Icon When Checking Discord, Specifically At The Bottom Left Corner Where It Suggests On Streaming The Game.

**To Reproduce**
1. Add An Icon For Every Available Option
2. Go To Any Discord Server
3. See The Icon Does Not Update On The Bottom Left

**Expected behavior**
The Icon Should Have Updated Or At Least Have A Separate Option

**Screenshots**
![image](https://user-images.githubusercontent.com/80133652/224450779-94d61553-f535-4358-a6c1-b0e63fcb8369.png)
**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11 Pro 22H2 22621.1265
 - JAVA Version: Java 8
 - Mod Version: 3.2.1
 - Discord Version: Ptb 179786 (bb147d5)
 - Minecraft Version: 1.19.2
 - Forge/Fabric Version: Fabric 0.14.17

**Additional context**
It Uses The Default Icon For The Mod.

**Comment by hypherionmc** [comment]
That icon cannot be modified by users. It's hardcoded into discord and has nothing do to with rpc.

**Comment by PolyframeX** [comment]
So I can't just like change a file or something?

**Comment by CDAGaming** [comment]
@PolyframeX To elaborate on the original answer, that icon is known as the Rich Presence Invite Image, as shown 
![image](https://user-images.githubusercontent.com/16328918/224463291-fb0bff18-bb26-45d4-9195-d2ad9d581036.png)

It is only modifyable, if you have access to the discord dev page for that client ID.

**Comment by PolyframeX** [comment]
Oh well okay then, thanks for elaborating. I suppose we might as well close the issue then, because it's impossible to fix.

**Comment by hypherionmc** [comment]
Just to add as well, that box doesn't show for everyone. For example, if you play Minecraft, you see that.

If I play Minecraft, I don't see that. It depends on if discord actually detects by itself that you are playing Minecraft (in which case it would show Playing Minecraft on your status) without using an RPC mod.
