### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DereC4** [hypherionmc/simple-rpc-public#6]
**Describe the bug**
Mod crashing on forge load

**To Reproduce**
Load 1.16.4 forge. Mod crashes on startup. 

**Expected behavior**
Mod was working before and displayed proper RPC info but now won't.

**Screenshots**
(none)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Window 64
 - JAVA Version: 1.8.0_271
 - Mod Version: 1.4.1
 - Minecraft Version: 1.16.4 
 - Forge Version: 35.1.0

**Additional context**
Error log reads
`Failure message: Simple RPC (simple-rpc) encountered an error during the common_setup event phase
		com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 45 column 6 path $.single_player.smallImageText
	Mod Version: 1.16.4-version
	Mod Issue URL: NOT PROVIDED
	Exception message: com.google.gson.stream.MalformedJsonException: Unterminated object at line 45 column 6 path $.single_player.smallImageText`

**Comment by hypherionmc** [comment]
Your JSON file is invalid. Copy the entire content of your file into this site and it will tell you what's wrong: https://jsonlint.com/
