### ISSUE TITLE
Question about 1.20

### ISSUE THREAD

**Issue by vico93** [hypherionmc/simple-rpc-public#63]
Hi! Is an 1.20 update on the radar?

**Comment by CDAGaming** [comment]
There is one already ready to go in a few days, please remain paitient.
It was delayed a bit while CurseForge stabilizes in the aftermath of the fractureizer attacks.

**Comment by hypherionmc** [comment]
And with mojang ALREADY dropping 1.20.1-rc1, it might be delayed a bit more... I don't want another repeat of doing a release, and then having to do a release the next day again because mojang broke something.

For now, the release is still scheduled for tomorrow, unless something changes

**Comment by hypherionmc** [comment]
1.20 was released today

**Comment by vico93** [comment]
> 1.20 was released today

thanks a lot! already using that!
