### ISSUE TITLE
[BUG] Russian language broken

### ISSUE THREAD

**Issue by RuZZnGG** [hypherionmc/simple-rpc-public#65]
Idk if it's a mod bug, but any russian text in rich presence is broken and every symbol is just a question mark.

Can't find any information about it, in 1.19.4 version of the mod everything was fine.
![image](https://github.com/hypherionmc/simple-rpc-public/assets/40216020/3b5efd17-6f96-4b5a-be9b-fdde553b8645)
![image](https://github.com/hypherionmc/simple-rpc-public/assets/40216020/3bc01266-be99-4cb1-82a9-d7e91c356032)

**Comment by hypherionmc** [comment]
I'm guessing you're referring to the 1.20 version.

Can you provide me with a copy of your config so I can test and fix it on my side please

**Comment by RuZZnGG** [comment]
Yes, it's 1.20 version.
Here is my config.
[simple-rpc.zip](https://github.com/hypherionmc/simple-rpc-public/files/11915056/simple-rpc.zip)

**Comment by hypherionmc** [comment]
Thanks. Will take a look at it over the weekend. Not at home tonight

**Comment by RuZZnGG** [comment]
Okay, waiting for your further message.

**Comment by hypherionmc** [comment]
So turns out this is a bug in CraterLib. Can you try with this build to see if it fixes the issue for you as well, before I make a release.

https://ci.firstdark.dev/job/CraterLib/job/1.20/

**Comment by RuZZnGG** [comment]
Yep, 1.0.20d fixes the issue, thanks!
![image](https://github.com/hypherionmc/simple-rpc-public/assets/40216020/6e598c5c-e894-4b8a-89eb-beb962b8eacb)

**Comment by hypherionmc** [comment]
Thanks. Will push a release tomorrow
