### ISSUE TITLE
[BUG] Crashing on 1.20.1

### ISSUE THREAD

**Issue by Ilovemyhous** [hypherionmc/simple-rpc-public#67]
**Describe the bug**
When launching the game (with Forge 1.20.1-47.1.0), it loads, then crashes with error code -1.

**To Reproduce**
_Assuming you already have the version of Forge installed that I mentioned above._
1. Download the mod.
1.1. Put it in your _mods_ folder.
2. Launch the game.
3. Crash.

**Expected behavior**
To not crash the game.

**Screenshots**
Here are all the mods that I use, maybe one doesn't like this mod.
![image](https://github.com/hypherionmc/simple-rpc-public/assets/50217071/dc38d3a9-c339-48fe-be1b-1c4af62d4360)
Crash
![image](https://github.com/hypherionmc/simple-rpc-public/assets/50217071/2c332ef1-7b66-4395-a570-ecb16c40aed3)

**Versions:**
 - OS:
 Windows 10 22H2 (Can also test on Linux if needed)
 
 - JAVA Version:
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) Client VM (build 25.371-b11, mixed mode, sharing)

 - Mod Version:
 simple-rpc-forge-1.20-3.2.2
 
 - Discord Version:
 Stable 211644 (7772b14)
 Host 1.0.9013 (34160)
 
 - Minecraft Version: 1.20.1
 - Forge/Fabric Version: Forge 1.20.1

**Additional context**
Crash log
[crash-2023-07-10_14.23.44-client.txt](https://github.com/hypherionmc/simple-rpc-public/files/12001821/crash-2023-07-10_14.23.44-client.txt)

**Comment by hypherionmc** [comment]
If you are using the java version in your report, it's the wrong version. Minecraft 1.18+ requires java 17

**Comment by hypherionmc** [comment]
If you are using the java version in your report, it's the wrong version. Minecraft 1.18+ requires java 17.


That aside. You are missing Craterlib which is a dependency of simple rpc and the config editor should not be in your mods folder.

The crash however doesn't appear to be from simple rpc, as the mixin causing the crash isn't one that's used by us (1.20+ simplerpc barely uses any mixins since Craterlib handles that)

**Comment by Ilovemyhous** [comment]
Hey!
This indeed solved my issue.
Sorry, I just updated the mod without checking the dependencies. ^^'
