### ISSUE TITLE
[BUG] Seperate Fabric and Forge

### ISSUE THREAD

**Issue by celsiusqc** [hypherionmc/simple-rpc-public#7]
Please seperate both projects so when I download the mod, it doesnt automatically download fabric api while I am using forge.

**Comment by hypherionmc** [comment]
Splitting them up now would be a terrible idea for me, but I can remove the Fabric API requirement on the Forge versions. I have no clue why Curseforge insists on adding them to every single file automatically

**Comment by hypherionmc** [comment]
I removed the fabric dependency on the 2.1 Forge files. I'll keep it like that in the future
