### ISSUE TITLE
[BUG] ReplayMod integration not working

### ISSUE THREAD

**Issue by TheCatRiX** [hypherionmc/simple-rpc-public#71]
**Describe the bug**
Special RPC for RepayMod not working

**To Reproduce**
1. Install ReplayMod and Simple Discord RPC together
2. Open Replay Browser/Replay Viewer/Replay Render
3. See wrong RPC

**Expected behavior**
Special RPC for ReplayMod

**Screenshots**
![screenshot](https://github.com/hypherionmc/simple-rpc-public/assets/58901923/7e8c8aeb-ddea-48e5-bbcf-505dccdad06a)

**Versions:**
 - OS: Windows 11
 - JAVA Version: 17
 - Mod Version: 3.2.2
 - Discord Version: Stable 220927 (520ba1a)
 - Minecraft Version: 1.20.1
 - Fabric Version: 0.14.22

**Comment by hypherionmc** [comment]
Ah okay, so when the mod was ported to 1.20, replay wasn't available yet, so the compat classes have been commented out. I will release an update re-enabling them.

Thanks for reporting

**Comment by hypherionmc** [comment]
Fix will be released along with the 1.20.2 port

**Comment by hypherionmc** [comment]
Feature is back with 3.2.4
