### ISSUE TITLE
does not allow any customization at all[BUG]

### ISSUE THREAD

**Issue by fourthhouse** [hypherionmc/simple-rpc-public#72]
**Describe the bug**
I've spent hours configuring this mod and even downloaded the "easy editor" from the mod creator's website. It simply does not work. It displays "Minecraft" "Playing Minecraft" as discord status, even after changing the config to what you want it to say. Even after using the downloadable app editor, and using that instead, it still does not work. 

**To Reproduce**
Download Modpack (For me, Sanctum Network on Curseforge)
Configure/Install Simple RPC mod

What Should Happen
It displays the edited rich presence status on your discord profile 

What happens 
It displays the default vanilla minecraft rich presence status on your discord profile

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
Sanctum Network CurseForge Modpack v4.2 
If you download Sanctum Network 4.2 that is exactly where the problem occurs. 
Forge 47.1.3
Simple RPC 3.2.2

**Additional context**
When configuring the mod using the downloadable app it even displays the proper preview using my custom text and images, so i know I configured my discord bot properly.  I will have to replace this with a different mod but I wish you luck with finding any incompatibilities and I hope I was able to help.

**Comment by hypherionmc** [comment]
If it keeps defaulting back to the default vanilla rpc, it means the config file failed to load. 

So if you can please share the config in question, as well as your log from when you ran the mod, so we can figure out what's going on there

**Comment by fourthhouse** [comment]
I'm so sorry for wasting your time but I realized I had two rich presence mods installed at the same time, your mod likely works perfectly fine and it was my fault. SORRY!!!! <3   I did spend hours trying to fix it and I just now realized another RPC mod is installed... clearly that was the issue

**Comment by fourthhouse** [comment]
This mod works perfect I was wrong sorry!!!

**Comment by hypherionmc** [comment]
That would do it lol. I see you had CraftPresence as well. That mod has a "config migrator" for simple rpc configs, so it would definitely cause some problems when the two are in the same game.

Glad you got it figured out
