### ISSUE TITLE
[Question/Suggestion] Keep default large icon/text when connecting to a server

### ISSUE THREAD

**Issue by 0xallie** [hypherionmc/simple-rpc-public#74]
Is there a way to keep the default large icon and its hover text when connecting to a server? If not, it would be nice to have an option for this. Currently it's just overridden by the server icon and "Playing on %server% with %players% players".

**Comment by 0xallie** [comment]
Well, I can do this by creating an explicit server entry override for each server, but I'd rather not do that.

**Comment by 0xallie** [comment]
It seems like the mod is hardcoded to do this for certain known servers, which I can work around in a couple other ways:

* Change the server address to an alias or add port
* Use my own Discord application ID, as it only does this for the default one

Still would be nice to have a toggle to disable this. And I would not override the large text even if enabled IMO, since that just provides redundancy with information that's already present in the default presets.

**Comment by hypherionmc** [comment]
The upcoming release will no longer override RPC information for "well known" servers.

Users can add these themselves if they wish to do so

**Comment by hypherionmc** [comment]
Change has been released with 3.2.4
