### ISSUE TITLE
[BUG] Crash on Fabric 1.20.2

### ISSUE THREAD

**Issue by 0xallie** [hypherionmc/simple-rpc-public#75]
**Describe the bug**
The game crashes when trying to use the mod on 1.20.2 with Fabric.

**To Reproduce**
1. Install Minecraft 1.20.2 and the latest versions of Fabric, Fabric API, CraterLib, Simple RPC
2. Try to start the game

**Expected behavior**
The game should not crash.

**Logs**
https://mclo.gs/R9pb4xb (is client, not server)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: macOS 14.0
 - Java Version: OpenJDK 17 (Temurin)
 - Mod Version: 3.2.4
 - Discord Version: Stable 232643 (1dbc00a)
 - Minecraft Version: 1.20.2
 - Forge/Fabric Version: Fabric Loader 0.14.22, Fabric API 0.89.3+1.20.2

**Comment by hypherionmc** [comment]
Oh shit. Oops. Will release a fix shortly

**Comment by hypherionmc** [comment]
Fix released. Thanks for reporting

**Comment by 0xallie** [comment]
Can confirm, fixed now.
