### ISSUE TITLE
Probably a stupid question  !  is it possible to make it so that it would show that you play minecraft but without logging into discord  [I can't use discord in the background]

### ISSUE THREAD

**Issue by MrSmi1ey** [hypherionmc/simple-rpc-public#76]
is it possible to make it so that it would show that you play minecraft but without logging into discord 
[I can't use discord in the background]

**Comment by hypherionmc** [comment]
Hey.

Unfortunately not. The Discord RPC api requires discord to be running and logged in (even if it's just running in the tray and not shown on screen). 

That's also why it doesn't work with Discord Web, since the actual RPC communication is done through your discord client
