### ISSUE TITLE
Can't get the image from %playerhead% variable

### ISSUE THREAD

**Issue by westahdusiwii** [hypherionmc/simple-rpc-public#80]
**Describe the bug**
No image in Rich Presence, if %playerhead% is set

**To Reproduce**
1. Set %playerhead% as any image
2. Check Discord activity

**Expected behavior**
Player head as image, I guess

**Screenshots**
If set as smallImageKey:
![image](https://github.com/hypherionmc/simple-rpc-public/assets/156493898/318a5078-75bb-49fa-9ca6-73d1ce34f3c8)
If set as largeImageKey:
![image](https://github.com/hypherionmc/simple-rpc-public/assets/156493898/17f2740e-60c6-40f9-8e07-c1f1334cb569)

**Versions:**
 - OS: Windows 10 22H2
 - JAVA Version: 17.0.9
 - Mod Version: 3.2.4
 - Discord Version: Stable 259048
 - Minecraft Version: 1.20.1
 - Fabric Version: 0.15.3

**Additional context**
Firstly, I tried found a solution here and on a wiki, thought maybe I misspelled something, but didn't find any solution.

**Comment by hypherionmc** [comment]
That might just be an outage on the service we use for the playerheads. It's a thirdparty service, so we don't have control over it.

However, if this doesn't resolve itself during the day, please let me know so I can investigate further

**Comment by westahdusiwii** [comment]
Yeah, I get it. I'll comment if nothing changes

**Comment by westahdusiwii** [comment]
So, everything is the same by now. 
![image](https://github.com/hypherionmc/simple-rpc-public/assets/156493898/9adf35e7-c78a-43a9-9dc9-d647bb84a3f8)

**Comment by westahdusiwii** [comment]
And here am I, once more. Idk, I tried everything already, checked the crafatar and other site to get my uuid. And they both working fine. Disabled all mods and still can't get the image. ;(
![image](https://github.com/hypherionmc/simple-rpc-public/assets/156493898/b5574140-2217-4ad1-8c8a-f7a2ed8c4132)

**Comment by hypherionmc** [comment]
Hey. Sorry it's been a hectic week. I will check this out tomorrow after work.

I wonder if this isn't the old issue we've fixed a couple of releases ago that came back now, where the player name was formatted from, so it wouldn't show the avatar. It only affected a handful of players

**Comment by westahdusiwii** [comment]
Oh man, sorry to hear that. I'll be patiently waiting. (Maybe will figure something out myself)
Good luck on work btw!

**Comment by hypherionmc** [comment]
So I finally got time to look into this.

Turns out, discord no longer likes cravatar (the service we use for heads).

When testing even with a direct link, the image doesn't load. 

So looks like we're going to be changing to mc-heads.net, which does still work. Busy doing the code changes now for it

**Comment by TheCatRiX** [comment]
While waiting for the fix, I realized that we can just use `https://mc-heads.net/avatar/%player%/64` instead of `%playerhead%`, it works fine.

**Comment by hypherionmc** [comment]
Should be properly fixed in the latest release
