### ISSUE TITLE
[BUG] Crash when trying to add the mod on my updated 1.21 modpack

### ISSUE THREAD

**Issue by vico93** [hypherionmc/simple-rpc-public#85]
**Describe the bug**
Basiaclly, the game crashes on start.

**To Reproduce**
1. Grab 'Simple RPC Universal 3.3.0' on Modrinth
2. Install on a 1.21 Fabric profile
3. Try to boot the game

**Versions:**
 - OS: Windows 11 x64
 - JAVA Version: 21.0.3, Microsoft
 - Mod Version: Universal 3.3.0
 - Minecraft Version: 1.21
 - Fabric Version: 0.15.11

[CRASH REPORT](https://gist.github.com/vico93/11daa229f74030022c5c61463c0573bf)

**Comment by hypherionmc** [comment]
Hey. Thanks for the report.

Please update to CraterLib `2.0.0+hotfix.1`. Stupid oversight that was missed during porting :( So sorry about that
