### ISSUE TITLE
[BUG] Event multi_player not working

### ISSUE THREAD

**Issue by BlankoPenguin** [hypherionmc/simple-rpc-public#86]
Event multi_player not working

when join in server event join_game still hang

**To Reproduce**
1. Go to 'servers'
2. Join to 'server'
3. Check discord status

**Expected behavior**
Event muilti_player must be working

![image](https://github.com/hypherionmc/simple-rpc-public/assets/129628671/94e6c8a1-f670-4717-90ec-4567822451f3)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Win10
 - JAVA Version: 21
 - Mod Version: [Universal 3.3.0](https://modrinth.com/mod/simple-discord-rpc/version/3.3.0)
 - Discord Version: stable 302556 (366c746) Host 1.0.9149 x64 (48589) Build Override: N/A Windows 10 64-bit (10.0.19045)
 - Minecraft Version: 1.21
 - Forge/Fabric Version: Fabric 0.15.11

mods:  
![image](https://github.com/hypherionmc/simple-rpc-public/assets/129628671/a6ad5f9f-dd48-4a43-a9bc-05a2dd55f73e)
not changed config

**Comment by hypherionmc** [comment]
Hey.

Can you maybe provide me with your game log? I've seen 2 or 3 reports of this, but the logs haven't been able to tell me anything about it.

If I can find the issue, I can fix it asap

**Comment by hypherionmc** [comment]
This build should fix the bug: https://nightbloom.cc/project/simplerpc/files/235

If you are willing to help confirm that it is fixed :)

**Comment by BlankoPenguin** [comment]
Bug fixed, yappi!

**Comment by johalun** [comment]
Fixed it for me too. MC 1.20.1, Forge.

**Comment by hypherionmc** [comment]
Release was made. Thanks for confirming the fix and reporting :)
