### ISSUE TITLE
[BUG] Severe lag when playing on another person's world via LAN/Direct Connection

### ISSUE THREAD

**Issue by CelestialAbyss** [hypherionmc/simple-rpc-public#88]
**Describe the bug**
Similar to this issue: https://github.com/hypherionmc/simple-rpc-public/issues/51 severe lag is encountered when trying to play on another player's world hosted via LAN or tunneling.

**To Reproduce**
1. Have Simple RPC & CraterLib installed.
2. Use either Essential or e4mc to join another player's world. Immediately notice the severe drop in FPS that repeats.
3. When both mods are removed, performance is restored.

**Expected behavior**

**Screenshots**
Spark was able to record this here: https://spark.lucko.me/TsPK2eaTgP

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11
 - JAVA Version: 17
 - Mod Version: 3.3.1
 - Discord Version: ptb 306495 (fb94650) Host 1.0.1089 x64 (49164) Build Override: N/A Windows 11 64-bit (10.0.22631)
 - Minecraft Version: 1.20.1
 - Forge/Fabric Version: 47.3.1

**Additional context**
This is clearly isolated to your mods as the increase in FPS was immediate upon removal.

**Comment by hypherionmc** [comment]
This is a "known" issue at this point, and we do finally know what causes the issue.

It's a thing added ages ago that is supposed to pull the player information from the server (for the player count placeholders), that fails on lan and direct connect servers, causing it to try over and over again, and causing the lag.

This will be completely removed in the up coming v4 releases, and will simply default to 0 if that info is missing. 


As far as we know, it only affects DIRECT connections and lan

**Comment by hypherionmc** [comment]
I'm going to be pushing a craterlib update in a day or two that will fix this issue. It will default the placeholders to player +1 for the missing details. Just working on 1 or 2 other things that also require the update to go out, so want to update them all at once

**Comment by hypherionmc** [comment]
Fixed in version 3.3.2. Requires CraterLib 2.0.1 for the fix to be effective
