### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by JamesTheFlash22** [hypherionmc/simple-rpc-public#89]
where can i find the config? i don't have the folder config
![image](https://github.com/hypherionmc/simple-rpc-public/assets/154464086/0c83468e-70a5-454f-ae34-c6995e9bf277)

**Comment by hypherionmc** [comment]
Why are you scratching in the mod jar?

The file is generated when the game is launched. There is nothing in the jar you can change to "make it load with default values". You need to launch the game with the mod installed, and the file will be generated in your minecraft config folder

**Comment by Fyoncle** [comment]
@hypherionmc why not close this issue yet lol

**Comment by hypherionmc** [comment]
Just not paying much attention to GitHub lol. I usually mass close issues with new releases

**Comment by Fyoncle** [comment]
> Just not paying much attention to GitHub lol. I usually mass close issues with new releases

Oh.

**Comment by JamesTheFlash22** [comment]
> Why are you scratching in the mod jar?
> 
> The file is generated when the game is launched. There is nothing in the jar you can change to "make it load with default values". You need to launch the game with the mod installed, and the file will be generated in your minecraft config folder

Ah ok, thanks
