### ISSUE TITLE
[BUG] Long log spamming by this mod. 

### ISSUE THREAD

**Issue by RustyBl0ck** [hypherionmc/simple-rpc-public#96]
**Describe the bug**
Long log spamming by this mod. 

LOG [This Link](https://mclo.gs/p9qujA7)

**Expected behavior**
No log spamming.

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: macOS Sonoma 14.5, M2 Pro Mac Mini
 - JAVA Version: 17
 - Mod Version: 3.3.3
 - Minecraft Version: 1.19.2
 - Forge/Fabric Version: 0.16.5 Fabric

**Additional context**

**Comment by hypherionmc** [comment]
Looks like a config issue. Can you send a copy of your config file as well please

**Comment by RustyBl0ck** [comment]
Hello! Thanks for replying! The files are hosted at: https://minossia.com/server-entries.toml and https://minossia.com/simple-rpc.toml

**Comment by hypherionmc** [comment]
Your simple-rpc.toml file is completely invalid.

You can't remove fields from the config file, like you did for [main_menu], [server_list] etc.

Setting the `enabled` flag under each section to `false` is all you need to do to disable them

**Comment by RustyBl0ck** [comment]
Oh, alright. I'm going to try the config again to see if its fine. Thanks for reaching out!

**Comment by RustyBl0ck** [comment]
The issue got fixed, thanks!
